id: I57B88E8E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T02:39:56+00:00'
last_modified: '2022-06-08T12:21:49.150893+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W12164
  title: ཕན་བདེའི་བསིལ་ཟེར་འཕྲོ་བའི་ཟླ་བ་གསར་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CCE9:
      image_group_id: I1KG20686
      title: ''
      total_pages: 638
      order: 1
      base_file: CCE9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
