id: P009626
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W12164
  title: ཕན་བདེའི་བསིལ་ཟེར་འཕྲོ་བའི་ཟླ་བ་གསར་པ།
  author: ''
  volumes:
    7c09b1df6b364108a7b08c33fac52cfe:
      image_group_id: I1KG20686
      title: ''
      volume_number: 1
      total_pages: 638
      base_file: v001.txt
